package org.ccguyka;

import net.gpedro.integrations.slack.SlackApi;
import net.gpedro.integrations.slack.SlackMessage;
import org.apache.commons.cli.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Slacker {

    private final Options options;

    public Slacker() {
        options = new Options();

        options.addRequiredOption("h", "hook", true, "Slack to hook");
        options.addRequiredOption("m", "message", true, "Message to be sent");
    }

    public static void main(String[] args) throws Exception {
        Slacker slacker = new Slacker();
        slacker.send(args);
    }

    private void send(String[] args) throws ParseException {
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse( options, args);

        String hook = cmd.getOptionValue("hook");
        String message = cmd.getOptionValue("message");

        SlackApi api = new SlackApi(hook);
        api.call(new SlackMessage(message));
    }
}
